language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - python ./src/manage.py validate_templates
  - pip check
  - pytest ./src/tests -s --cov-fail-under=15
env:
  - SECRET_KEY=supersecretkey
  - SERVER=dev
  - ALLOWED_HOSTS=127.0.0.1:localhost:*
