SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_TEST1 = 3
SOURCE_TEST2 = 4
SOURCE_TEST3 = 5
SOURCE_TEST4 = 6
SOURCE_AVAL = 7

SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_TEST2, 'SOURCE_TEST2'),
    (SOURCE_TEST3, 'SOURCE_TEST3'),
    (SOURCE_TEST4, 'SOURCE_TEST4'),
    (SOURCE_AVAL, 'Aval'),
)

CURRENCY_TYPE_USD = 1
CURRENCY_TYPE_EUR = 2
CURRENCY_TYPE_RUR = 3
CURRENCY_TYPE_BTC = 4
CURRENCY_TYPE_CHOICES = (
    (CURRENCY_TYPE_USD, 'USD'),
    (CURRENCY_TYPE_EUR, 'EUR'),
    (CURRENCY_TYPE_RUR, 'RUR'),
    (CURRENCY_TYPE_BTC, 'BTC'),
)

RATE_TYPE_SALE = 1
RATE_TYPE_BUY = 2
RATE_TYPE_CHOICES = (
    (RATE_TYPE_SALE, 'Sale'),
    (RATE_TYPE_BUY, 'Buy'),
)
