# Generated by Django 2.2.12 on 2020-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'RUR'), (4, 'BTC')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (4, 'SOURCE_TEST2'), (5, 'SOURCE_TEST3'), (6, 'SOURCE_TEST4')]),
        ),
    ]
