# Generated by Django 2.2.13 on 2020-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200607_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (4, 'SOURCE_TEST2'), (5, 'SOURCE_TEST3'), (6, 'SOURCE_TEST4'), (7, 'Aval')]),
        ),
    ]
